import type {
  ThemeColourPalette,
  ThemeConfiguration,
  ThemeLayout,
  ThemeNiche,
  ThemeSection,
} from "@/lib/theme/types";
const defaultSections: ThemeSection[] = [
  {
    id: "hero",
    type: "hero",
    title: "Top Stories",
    enabled: true,
    position: 1,
    articleLimit: 5,
  },
  {
    id: "featured",
    type: "featured",
    title: "Featured",
    enabled: true,
    position: 2,
    articleLimit: 6,
  },
  {
    id: "latest",
    type: "latest",
    title: "Latest Articles",
    enabled: true,
    position: 3,
    articleLimit: 12,
  },
  {
    id: "trending",
    type: "trending",
    title: "Trending",
    enabled: true,
    position: 4,
    articleLimit: 8,
  },
  {
    id: "newsletter",
    type: "newsletter",
    title: "Newsletter",
    enabled: true,
    position: 5,
    articleLimit: 0,
  },
];
const palettes: Record<ThemeNiche, ThemeColourPalette> = {
  news: {
    background: "#ffffff",
    foreground: "#111827",
    primary: "#b91c1c",
    secondary: "#1f2937",
    accent: "#f59e0b",
    muted: "#f3f4f6",
    border: "#d1d5db",
  },
  finance: {
    background: "#f8fafc",
    foreground: "#0f172a",
    primary: "#047857",
    secondary: "#0f766e",
    accent: "#ca8a04",
    muted: "#ecfdf5",
    border: "#cbd5e1",
  },
  technology: {
    background: "#020617",
    foreground: "#f8fafc",
    primary: "#2563eb",
    secondary: "#7c3aed",
    accent: "#06b6d4",
    muted: "#0f172a",
    border: "#334155",
  },
  ai: {
    background: "#09090b",
    foreground: "#fafafa",
    primary: "#8b5cf6",
    secondary: "#ec4899",
    accent: "#22d3ee",
    muted: "#18181b",
    border: "#3f3f46",
  },
  business: {
    background: "#ffffff",
    foreground: "#172554",
    primary: "#1d4ed8",
    secondary: "#334155",
    accent: "#f59e0b",
    muted: "#eff6ff",
    border: "#cbd5e1",
  },
  education: {
    background: "#fffbeb",
    foreground: "#422006",
    primary: "#d97706",
    secondary: "#92400e",
    accent: "#2563eb",
    muted: "#fef3c7",
    border: "#fcd34d",
  },
  health: {
    background: "#f0fdf4",
    foreground: "#14532d",
    primary: "#16a34a",
    secondary: "#0f766e",
    accent: "#0284c7",
    muted: "#dcfce7",
    border: "#86efac",
  },
  science: {
    background: "#f8fafc",
    foreground: "#1e1b4b",
    primary: "#4338ca",
    secondary: "#0369a1",
    accent: "#7c3aed",
    muted: "#eef2ff",
    border: "#c7d2fe",
  },
  fashion: {
    background: "#fff7ed",
    foreground: "#431407",
    primary: "#e11d48",
    secondary: "#9f1239",
    accent: "#fb7185",
    muted: "#ffe4e6",
    border: "#fecdd3",
  },
  beauty: {
    background: "#fdf4ff",
    foreground: "#4a044e",
    primary: "#c026d3",
    secondary: "#db2777",
    accent: "#f472b6",
    muted: "#fae8ff",
    border: "#f5d0fe",
  },
  cars: {
    background: "#09090b",
    foreground: "#fafafa",
    primary: "#dc2626",
    secondary: "#27272a",
    accent: "#f97316",
    muted: "#18181b",
    border: "#3f3f46",
  },
  sports: {
    background: "#f8fafc",
    foreground: "#052e16",
    primary: "#15803d",
    secondary: "#166534",
    accent: "#eab308",
    muted: "#dcfce7",
    border: "#86efac",
  },
  travel: {
    background: "#ecfeff",
    foreground: "#164e63",
    primary: "#0891b2",
    secondary: "#0369a1",
    accent: "#f97316",
    muted: "#cffafe",
    border: "#67e8f9",
  },
  food: {
    background: "#fff7ed",
    foreground: "#431407",
    primary: "#ea580c",
    secondary: "#b45309",
    accent: "#65a30d",
    muted: "#ffedd5",
    border: "#fdba74",
  },
  gaming: {
    background: "#020617",
    foreground: "#f8fafc",
    primary: "#7c3aed",
    secondary: "#2563eb",
    accent: "#22c55e",
    muted: "#0f172a",
    border: "#334155",
  },
  entertainment: {
    background: "#18181b",
    foreground: "#fafafa",
    primary: "#db2777",
    secondary: "#7c3aed",
    accent: "#f59e0b",
    muted: "#27272a",
    border: "#52525b",
  },
  "real-estate": {
    background: "#f8fafc",
    foreground: "#1e293b",
    primary: "#0f766e",
    secondary: "#475569",
    accent: "#d97706",
    muted: "#f1f5f9",
    border: "#cbd5e1",
  },
  agriculture: {
    background: "#f7fee7",
    foreground: "#365314",
    primary: "#4d7c0f",
    secondary: "#3f6212",
    accent: "#ca8a04",
    muted: "#ecfccb",
    border: "#bef264",
  },
  lifestyle: {
    background: "#fdf2f8",
    foreground: "#500724",
    primary: "#be185d",
    secondary: "#7e22ce",
    accent: "#f59e0b",
    muted: "#fce7f3",
    border: "#f9a8d4",
  },
  general: {
    background: "#ffffff",
    foreground: "#0f172a",
    primary: "#2563eb",
    secondary: "#475569",
    accent: "#7c3aed",
    muted: "#f1f5f9",
    border: "#cbd5e1",
  },
};
const layouts: Partial<Record<ThemeNiche, ThemeLayout>> = {
  news: "editorial",
  finance: "business",
  technology: "grid",
  ai: "grid",
  fashion: "visual",
  beauty: "visual",
  cars: "visual",
  entertainment: "magazine",
  general: "magazine",
};
const navigationByNiche: Record<ThemeNiche, string[]> = {
  news: ["Latest", "Politics", "World", "Business", "Sports", "Culture"],
  finance: ["Markets", "Economy", "Investing", "Banking", "Personal Finance"],
  technology: ["Technology", "AI", "Software", "Hardware", "Cybersecurity"],
  ai: ["Artificial Intelligence", "Tools", "Research", "Automation", "Robotics"],
  business: ["Business", "Startups", "Leadership", "Marketing", "Careers"],
  education: ["Education", "Learning", "Courses", "Students", "Teachers"],
  health: ["Health", "Fitness", "Nutrition", "Wellness", "Medicine"],
  science: ["Science", "Research", "Space", "Environment", "Innovation"],
  fashion: ["Fashion", "Clothing", "Trends", "Designers", "Style"],
  beauty: ["Beauty", "Skincare", "Makeup", "Hair", "Wellness"],
  cars: ["Cars", "Reviews", "Electric Vehicles", "Performance", "Industry"],
  sports: ["Sports", "Football", "Cricket", "Tennis", "Fitness"],
  travel: ["Travel", "Destinations", "Hotels", "Guides", "Adventure"],
  food: ["Food", "Recipes", "Restaurants", "Nutrition", "Cooking"],
  gaming: ["Gaming", "PC", "Console", "Mobile", "Esports"],
  entertainment: ["Entertainment", "Movies", "Television", "Music", "Celebrities"],
  "real-estate": ["Real Estate", "Property", "Investment", "Homes", "Commercial"],
  agriculture: ["Agriculture", "Farming", "Crops", "Livestock", "Technology"],
  lifestyle: ["Lifestyle", "Home", "Relationships", "Travel", "Wellness"],
  general: ["Latest", "Popular", "Technology", "Business", "Lifestyle"],
};
function createPreset(niche: ThemeNiche, name: string): ThemeConfiguration {
  const timestamp = new Date().toISOString();
  return {
    id: `${niche}-preset`,
    name,
    niche,
    layout: layouts[niche] ?? "magazine",
    version: 1,
    isActive: niche === "general",
    colours: palettes[niche],
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 700,
      bodyWeight: 400,
    },
    sections: defaultSections.map((section) => ({ ...section })),
    navigation: [...navigationByNiche[niche]],
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}
export const themePresets: ThemeConfiguration[] = [
  createPreset("general", "Knowledge Nest"),
  createPreset("news", "Breaking News"),
  createPreset("finance", "Finance Ledger"),
  createPreset("technology", "Technology Grid"),
  createPreset("ai", "AI Horizon"),
  createPreset("business", "Business Professional"),
  createPreset("education", "Learning Centre"),
  createPreset("health", "Health Journal"),
  createPreset("science", "Science Explorer"),
  createPreset("fashion", "Fashion Editorial"),
  createPreset("beauty", "Beauty Studio"),
  createPreset("cars", "Automotive Performance"),
  createPreset("sports", "Sports Arena"),
  createPreset("travel", "Travel Explorer"),
  createPreset("food", "Food Magazine"),
  createPreset("gaming", "Gaming Universe"),
  createPreset("entertainment", "Entertainment Daily"),
  createPreset("real-estate", "Property Market"),
  createPreset("agriculture", "Agriculture Today"),
  createPreset("lifestyle", "Modern Lifestyle"),
];
export function createThemeFromNiche(
  niche: ThemeNiche,
  name?: string,
): ThemeConfiguration {
  const preset =
    themePresets.find((theme) => theme.niche === niche) ??
    themePresets.find((theme) => theme.niche === "general")!;
  const timestamp = new Date().toISOString();
  return {
    ...structuredClone(preset),
    id: `${niche}-${Date.now()}`,
    name: name?.trim() || preset.name,
    isActive: false,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}
